#!/bin/sh
set -e

echo ""
echo "====================================="
echo "  cnmsb (操你妈傻逼) 安装成功！"
echo "====================================="
echo ""
echo "使用方法："
echo ""
echo "  Bash: echo 'eval \"\$(cnmsb init bash)\"' >> ~/.bashrc"
echo "  Zsh:  echo 'eval \"\$(cnmsb init zsh)\"' >> ~/.zshrc"
echo ""
echo "或者手动加载："
echo "  source /usr/share/cnmsb/cnmsb.bash"
echo "  source /usr/share/cnmsb/cnmsb.zsh"
echo ""

exit 0
