//! PostgreSQL 语法定义

use super::common::{SqlCompletion, SqlSyntax};

/// PostgreSQL 语法
pub struct PostgreSqlSyntax;

impl SqlSyntax for PostgreSqlSyntax {
    fn keywords(&self) -> Vec<SqlCompletion> {
        vec![
            // DML
            SqlCompletion::keyword("SELECT", "查询数据"),
            SqlCompletion::keyword("INSERT", "插入数据"),
            SqlCompletion::keyword("UPDATE", "更新数据"),
            SqlCompletion::keyword("DELETE", "删除数据"),
            SqlCompletion::keyword("UPSERT", "更新或插入"),
            
            // 子句
            SqlCompletion::keyword("FROM", "数据来源"),
            SqlCompletion::keyword("WHERE", "条件过滤"),
            SqlCompletion::keyword("AND", "与条件"),
            SqlCompletion::keyword("OR", "或条件"),
            SqlCompletion::keyword("NOT", "非条件"),
            SqlCompletion::keyword("IN", "包含"),
            SqlCompletion::keyword("LIKE", "模糊匹配"),
            SqlCompletion::keyword("ILIKE", "不区分大小写匹配"),
            SqlCompletion::keyword("SIMILAR TO", "相似匹配"),
            SqlCompletion::keyword("BETWEEN", "范围"),
            SqlCompletion::keyword("IS NULL", "空值判断"),
            SqlCompletion::keyword("IS NOT NULL", "非空判断"),
            SqlCompletion::keyword("EXISTS", "存在判断"),
            SqlCompletion::keyword("ORDER BY", "排序"),
            SqlCompletion::keyword("GROUP BY", "分组"),
            SqlCompletion::keyword("HAVING", "分组过滤"),
            SqlCompletion::keyword("LIMIT", "限制行数"),
            SqlCompletion::keyword("OFFSET", "偏移量"),
            SqlCompletion::keyword("FETCH FIRST", "获取前N行"),
            SqlCompletion::keyword("DISTINCT", "去重"),
            SqlCompletion::keyword("DISTINCT ON", "按列去重"),
            SqlCompletion::keyword("AS", "别名"),
            SqlCompletion::keyword("ON", "连接条件"),
            SqlCompletion::keyword("USING", "使用列连接"),
            SqlCompletion::keyword("RETURNING", "返回值"),
            SqlCompletion::keyword("ON CONFLICT", "冲突处理"),
            SqlCompletion::keyword("DO NOTHING", "不做操作"),
            SqlCompletion::keyword("DO UPDATE", "执行更新"),
            
            // JOIN
            SqlCompletion::keyword("JOIN", "连接表"),
            SqlCompletion::keyword("INNER JOIN", "内连接"),
            SqlCompletion::keyword("LEFT JOIN", "左连接"),
            SqlCompletion::keyword("LEFT OUTER JOIN", "左外连接"),
            SqlCompletion::keyword("RIGHT JOIN", "右连接"),
            SqlCompletion::keyword("RIGHT OUTER JOIN", "右外连接"),
            SqlCompletion::keyword("FULL JOIN", "全连接"),
            SqlCompletion::keyword("FULL OUTER JOIN", "全外连接"),
            SqlCompletion::keyword("CROSS JOIN", "交叉连接"),
            SqlCompletion::keyword("NATURAL JOIN", "自然连接"),
            SqlCompletion::keyword("LATERAL", "横向连接"),
            
            // UNION/INTERSECT/EXCEPT
            SqlCompletion::keyword("UNION", "合并结果"),
            SqlCompletion::keyword("UNION ALL", "合并所有结果"),
            SqlCompletion::keyword("INTERSECT", "交集"),
            SqlCompletion::keyword("EXCEPT", "差集"),
            
            // CTE
            SqlCompletion::keyword("WITH", "公共表表达式"),
            SqlCompletion::keyword("WITH RECURSIVE", "递归CTE"),
            
            // DDL
            SqlCompletion::keyword("CREATE", "创建对象"),
            SqlCompletion::keyword("CREATE TABLE", "创建表"),
            SqlCompletion::keyword("CREATE DATABASE", "创建数据库"),
            SqlCompletion::keyword("CREATE SCHEMA", "创建模式"),
            SqlCompletion::keyword("CREATE INDEX", "创建索引"),
            SqlCompletion::keyword("CREATE UNIQUE INDEX", "创建唯一索引"),
            SqlCompletion::keyword("CREATE VIEW", "创建视图"),
            SqlCompletion::keyword("CREATE MATERIALIZED VIEW", "创建物化视图"),
            SqlCompletion::keyword("CREATE FUNCTION", "创建函数"),
            SqlCompletion::keyword("CREATE PROCEDURE", "创建存储过程"),
            SqlCompletion::keyword("CREATE TRIGGER", "创建触发器"),
            SqlCompletion::keyword("CREATE SEQUENCE", "创建序列"),
            SqlCompletion::keyword("CREATE TYPE", "创建类型"),
            SqlCompletion::keyword("CREATE EXTENSION", "创建扩展"),
            SqlCompletion::keyword("CREATE ROLE", "创建角色"),
            SqlCompletion::keyword("CREATE USER", "创建用户"),
            SqlCompletion::keyword("ALTER", "修改对象"),
            SqlCompletion::keyword("ALTER TABLE", "修改表"),
            SqlCompletion::keyword("ALTER DATABASE", "修改数据库"),
            SqlCompletion::keyword("ALTER SCHEMA", "修改模式"),
            SqlCompletion::keyword("ALTER SEQUENCE", "修改序列"),
            SqlCompletion::keyword("DROP", "删除对象"),
            SqlCompletion::keyword("DROP TABLE", "删除表"),
            SqlCompletion::keyword("DROP DATABASE", "删除数据库"),
            SqlCompletion::keyword("DROP SCHEMA", "删除模式"),
            SqlCompletion::keyword("DROP INDEX", "删除索引"),
            SqlCompletion::keyword("TRUNCATE", "清空表"),
            SqlCompletion::keyword("TRUNCATE TABLE", "清空表"),
            
            // 表结构
            SqlCompletion::keyword("ADD", "添加列"),
            SqlCompletion::keyword("ADD COLUMN", "添加列"),
            SqlCompletion::keyword("DROP COLUMN", "删除列"),
            SqlCompletion::keyword("ALTER COLUMN", "修改列"),
            SqlCompletion::keyword("RENAME COLUMN", "重命名列"),
            SqlCompletion::keyword("RENAME TO", "重命名"),
            SqlCompletion::keyword("SET DATA TYPE", "设置类型"),
            SqlCompletion::keyword("SET DEFAULT", "设置默认值"),
            SqlCompletion::keyword("DROP DEFAULT", "删除默认值"),
            SqlCompletion::keyword("SET NOT NULL", "设置非空"),
            SqlCompletion::keyword("DROP NOT NULL", "删除非空"),
            SqlCompletion::keyword("PRIMARY KEY", "主键"),
            SqlCompletion::keyword("FOREIGN KEY", "外键"),
            SqlCompletion::keyword("UNIQUE", "唯一约束"),
            SqlCompletion::keyword("CHECK", "检查约束"),
            SqlCompletion::keyword("CONSTRAINT", "约束"),
            SqlCompletion::keyword("DEFAULT", "默认值"),
            SqlCompletion::keyword("NOT NULL", "非空约束"),
            SqlCompletion::keyword("SERIAL", "自增整数"),
            SqlCompletion::keyword("BIGSERIAL", "大自增整数"),
            SqlCompletion::keyword("GENERATED", "生成列"),
            SqlCompletion::keyword("IDENTITY", "标识列"),
            SqlCompletion::keyword("REFERENCES", "引用"),
            SqlCompletion::keyword("ON DELETE", "删除时"),
            SqlCompletion::keyword("ON UPDATE", "更新时"),
            SqlCompletion::keyword("CASCADE", "级联"),
            SqlCompletion::keyword("SET NULL", "置空"),
            SqlCompletion::keyword("RESTRICT", "限制"),
            SqlCompletion::keyword("NO ACTION", "无操作"),
            SqlCompletion::keyword("IF EXISTS", "如果存在"),
            SqlCompletion::keyword("IF NOT EXISTS", "如果不存在"),
            SqlCompletion::keyword("CONCURRENTLY", "并发"),
            
            // DCL
            SqlCompletion::keyword("GRANT", "授权"),
            SqlCompletion::keyword("REVOKE", "撤销权限"),
            
            // TCL
            SqlCompletion::keyword("BEGIN", "开始事务"),
            SqlCompletion::keyword("COMMIT", "提交事务"),
            SqlCompletion::keyword("ROLLBACK", "回滚事务"),
            SqlCompletion::keyword("SAVEPOINT", "保存点"),
            SqlCompletion::keyword("RELEASE SAVEPOINT", "释放保存点"),
            SqlCompletion::keyword("ROLLBACK TO", "回滚到保存点"),
            
            // 其他
            SqlCompletion::keyword("EXPLAIN", "执行计划"),
            SqlCompletion::keyword("EXPLAIN ANALYZE", "分析执行计划"),
            SqlCompletion::keyword("VACUUM", "清理"),
            SqlCompletion::keyword("VACUUM FULL", "完全清理"),
            SqlCompletion::keyword("ANALYZE", "分析统计"),
            SqlCompletion::keyword("REINDEX", "重建索引"),
            SqlCompletion::keyword("REFRESH MATERIALIZED VIEW", "刷新物化视图"),
            SqlCompletion::keyword("SET", "设置变量"),
            SqlCompletion::keyword("SHOW", "显示变量"),
            SqlCompletion::keyword("COPY", "复制数据"),
            SqlCompletion::keyword("INTO", "插入目标"),
            SqlCompletion::keyword("VALUES", "值列表"),
            SqlCompletion::keyword("CASE", "条件表达式"),
            SqlCompletion::keyword("WHEN", "当"),
            SqlCompletion::keyword("THEN", "则"),
            SqlCompletion::keyword("ELSE", "否则"),
            SqlCompletion::keyword("END", "结束"),
            SqlCompletion::keyword("COALESCE", "第一个非空"),
            SqlCompletion::keyword("NULLIF", "相等返回空"),
            SqlCompletion::keyword("GREATEST", "最大值"),
            SqlCompletion::keyword("LEAST", "最小值"),
            SqlCompletion::keyword("ASC", "升序"),
            SqlCompletion::keyword("DESC", "降序"),
            SqlCompletion::keyword("NULLS FIRST", "空值在前"),
            SqlCompletion::keyword("NULLS LAST", "空值在后"),
            SqlCompletion::keyword("TRUE", "真"),
            SqlCompletion::keyword("FALSE", "假"),
            SqlCompletion::keyword("NULL", "空值"),
            SqlCompletion::keyword("ARRAY", "数组"),
            SqlCompletion::keyword("ROW", "行"),
            SqlCompletion::keyword("FOR UPDATE", "行锁"),
            SqlCompletion::keyword("FOR SHARE", "共享锁"),
            SqlCompletion::keyword("NOWAIT", "不等待"),
            SqlCompletion::keyword("SKIP LOCKED", "跳过锁定行"),
        ]
    }
    
    fn functions(&self) -> Vec<SqlCompletion> {
        vec![
            // 聚合函数
            SqlCompletion::function("COUNT()", "计数"),
            SqlCompletion::function("SUM()", "求和"),
            SqlCompletion::function("AVG()", "平均值"),
            SqlCompletion::function("MAX()", "最大值"),
            SqlCompletion::function("MIN()", "最小值"),
            SqlCompletion::function("ARRAY_AGG()", "聚合为数组"),
            SqlCompletion::function("STRING_AGG()", "聚合为字符串"),
            SqlCompletion::function("JSON_AGG()", "聚合为 JSON 数组"),
            SqlCompletion::function("JSONB_AGG()", "聚合为 JSONB 数组"),
            SqlCompletion::function("JSON_OBJECT_AGG()", "聚合为 JSON 对象"),
            SqlCompletion::function("BOOL_AND()", "布尔与"),
            SqlCompletion::function("BOOL_OR()", "布尔或"),
            SqlCompletion::function("BIT_AND()", "位与"),
            SqlCompletion::function("BIT_OR()", "位或"),
            SqlCompletion::function("EVERY()", "所有为真"),
            
            // 窗口函数
            SqlCompletion::function("ROW_NUMBER()", "行号"),
            SqlCompletion::function("RANK()", "排名"),
            SqlCompletion::function("DENSE_RANK()", "密集排名"),
            SqlCompletion::function("PERCENT_RANK()", "百分比排名"),
            SqlCompletion::function("CUME_DIST()", "累积分布"),
            SqlCompletion::function("NTILE()", "分桶"),
            SqlCompletion::function("LAG()", "上一行"),
            SqlCompletion::function("LEAD()", "下一行"),
            SqlCompletion::function("FIRST_VALUE()", "第一个值"),
            SqlCompletion::function("LAST_VALUE()", "最后一个值"),
            SqlCompletion::function("NTH_VALUE()", "第 N 个值"),
            
            // 字符串函数
            SqlCompletion::function("CONCAT()", "连接字符串"),
            SqlCompletion::function("CONCAT_WS()", "带分隔符连接"),
            SqlCompletion::function("SUBSTRING()", "子字符串"),
            SqlCompletion::function("LEFT()", "左截取"),
            SqlCompletion::function("RIGHT()", "右截取"),
            SqlCompletion::function("LENGTH()", "长度"),
            SqlCompletion::function("CHAR_LENGTH()", "字符长度"),
            SqlCompletion::function("OCTET_LENGTH()", "字节长度"),
            SqlCompletion::function("UPPER()", "转大写"),
            SqlCompletion::function("LOWER()", "转小写"),
            SqlCompletion::function("INITCAP()", "首字母大写"),
            SqlCompletion::function("TRIM()", "去空格"),
            SqlCompletion::function("LTRIM()", "去左空格"),
            SqlCompletion::function("RTRIM()", "去右空格"),
            SqlCompletion::function("BTRIM()", "去两边空格"),
            SqlCompletion::function("REPLACE()", "替换"),
            SqlCompletion::function("TRANSLATE()", "翻译字符"),
            SqlCompletion::function("REVERSE()", "反转"),
            SqlCompletion::function("LPAD()", "左填充"),
            SqlCompletion::function("RPAD()", "右填充"),
            SqlCompletion::function("POSITION()", "查找位置"),
            SqlCompletion::function("STRPOS()", "查找位置"),
            SqlCompletion::function("FORMAT()", "格式化"),
            SqlCompletion::function("REPEAT()", "重复字符串"),
            SqlCompletion::function("ASCII()", "ASCII 码"),
            SqlCompletion::function("CHR()", "ASCII 字符"),
            SqlCompletion::function("SPLIT_PART()", "分割取部分"),
            SqlCompletion::function("REGEXP_REPLACE()", "正则替换"),
            SqlCompletion::function("REGEXP_MATCH()", "正则匹配"),
            SqlCompletion::function("REGEXP_MATCHES()", "正则匹配所有"),
            SqlCompletion::function("REGEXP_SPLIT_TO_ARRAY()", "正则分割为数组"),
            SqlCompletion::function("REGEXP_SPLIT_TO_TABLE()", "正则分割为表"),
            
            // 数学函数
            SqlCompletion::function("ABS()", "绝对值"),
            SqlCompletion::function("CEIL()", "向上取整"),
            SqlCompletion::function("CEILING()", "向上取整"),
            SqlCompletion::function("FLOOR()", "向下取整"),
            SqlCompletion::function("ROUND()", "四舍五入"),
            SqlCompletion::function("TRUNC()", "截断"),
            SqlCompletion::function("MOD()", "取模"),
            SqlCompletion::function("POWER()", "幂"),
            SqlCompletion::function("SQRT()", "平方根"),
            SqlCompletion::function("CBRT()", "立方根"),
            SqlCompletion::function("EXP()", "指数"),
            SqlCompletion::function("LN()", "自然对数"),
            SqlCompletion::function("LOG()", "对数"),
            SqlCompletion::function("LOG10()", "常用对数"),
            SqlCompletion::function("RANDOM()", "随机数"),
            SqlCompletion::function("SETSEED()", "设置随机种子"),
            SqlCompletion::function("SIGN()", "符号"),
            SqlCompletion::function("PI()", "圆周率"),
            SqlCompletion::function("DEGREES()", "弧度转角度"),
            SqlCompletion::function("RADIANS()", "角度转弧度"),
            SqlCompletion::function("SIN()", "正弦"),
            SqlCompletion::function("COS()", "余弦"),
            SqlCompletion::function("TAN()", "正切"),
            SqlCompletion::function("ASIN()", "反正弦"),
            SqlCompletion::function("ACOS()", "反余弦"),
            SqlCompletion::function("ATAN()", "反正切"),
            SqlCompletion::function("ATAN2()", "二参数反正切"),
            SqlCompletion::function("COT()", "余切"),
            
            // 日期时间函数
            SqlCompletion::function("NOW()", "当前时间"),
            SqlCompletion::function("CURRENT_DATE", "当前日期"),
            SqlCompletion::function("CURRENT_TIME", "当前时间"),
            SqlCompletion::function("CURRENT_TIMESTAMP", "当前时间戳"),
            SqlCompletion::function("LOCALTIME", "本地时间"),
            SqlCompletion::function("LOCALTIMESTAMP", "本地时间戳"),
            SqlCompletion::function("DATE_PART()", "提取日期部分"),
            SqlCompletion::function("DATE_TRUNC()", "截断日期"),
            SqlCompletion::function("EXTRACT()", "提取日期部分"),
            SqlCompletion::function("AGE()", "年龄/间隔"),
            SqlCompletion::function("CLOCK_TIMESTAMP()", "时钟时间戳"),
            SqlCompletion::function("STATEMENT_TIMESTAMP()", "语句时间戳"),
            SqlCompletion::function("TRANSACTION_TIMESTAMP()", "事务时间戳"),
            SqlCompletion::function("MAKE_DATE()", "构造日期"),
            SqlCompletion::function("MAKE_TIME()", "构造时间"),
            SqlCompletion::function("MAKE_TIMESTAMP()", "构造时间戳"),
            SqlCompletion::function("MAKE_INTERVAL()", "构造间隔"),
            SqlCompletion::function("TO_CHAR()", "格式化输出"),
            SqlCompletion::function("TO_DATE()", "转换为日期"),
            SqlCompletion::function("TO_TIMESTAMP()", "转换为时间戳"),
            SqlCompletion::function("ISFINITE()", "是否有限"),
            
            // JSON/JSONB 函数
            SqlCompletion::function("JSON_BUILD_OBJECT()", "构建 JSON 对象"),
            SqlCompletion::function("JSON_BUILD_ARRAY()", "构建 JSON 数组"),
            SqlCompletion::function("TO_JSON()", "转为 JSON"),
            SqlCompletion::function("TO_JSONB()", "转为 JSONB"),
            SqlCompletion::function("JSON_ARRAY_LENGTH()", "JSON 数组长度"),
            SqlCompletion::function("JSONB_ARRAY_LENGTH()", "JSONB 数组长度"),
            SqlCompletion::function("JSON_EACH()", "遍历 JSON"),
            SqlCompletion::function("JSONB_EACH()", "遍历 JSONB"),
            SqlCompletion::function("JSON_EACH_TEXT()", "遍历 JSON 文本"),
            SqlCompletion::function("JSONB_EACH_TEXT()", "遍历 JSONB 文本"),
            SqlCompletion::function("JSON_EXTRACT_PATH()", "提取 JSON 路径"),
            SqlCompletion::function("JSONB_EXTRACT_PATH()", "提取 JSONB 路径"),
            SqlCompletion::function("JSON_EXTRACT_PATH_TEXT()", "提取 JSON 路径文本"),
            SqlCompletion::function("JSONB_EXTRACT_PATH_TEXT()", "提取 JSONB 路径文本"),
            SqlCompletion::function("JSON_OBJECT_KEYS()", "JSON 对象键"),
            SqlCompletion::function("JSONB_OBJECT_KEYS()", "JSONB 对象键"),
            SqlCompletion::function("JSON_TYPEOF()", "JSON 类型"),
            SqlCompletion::function("JSONB_TYPEOF()", "JSONB 类型"),
            SqlCompletion::function("JSON_STRIP_NULLS()", "移除 NULL"),
            SqlCompletion::function("JSONB_STRIP_NULLS()", "移除 NULL"),
            SqlCompletion::function("JSONB_SET()", "设置 JSONB 值"),
            SqlCompletion::function("JSONB_INSERT()", "插入 JSONB 值"),
            SqlCompletion::function("JSONB_PRETTY()", "美化 JSONB"),
            
            // 数组函数
            SqlCompletion::function("ARRAY_LENGTH()", "数组长度"),
            SqlCompletion::function("ARRAY_DIMS()", "数组维度"),
            SqlCompletion::function("ARRAY_UPPER()", "数组上界"),
            SqlCompletion::function("ARRAY_LOWER()", "数组下界"),
            SqlCompletion::function("ARRAY_APPEND()", "追加元素"),
            SqlCompletion::function("ARRAY_PREPEND()", "前置元素"),
            SqlCompletion::function("ARRAY_CAT()", "连接数组"),
            SqlCompletion::function("ARRAY_REMOVE()", "移除元素"),
            SqlCompletion::function("ARRAY_REPLACE()", "替换元素"),
            SqlCompletion::function("ARRAY_POSITION()", "元素位置"),
            SqlCompletion::function("ARRAY_POSITIONS()", "所有位置"),
            SqlCompletion::function("ARRAY_TO_STRING()", "数组转字符串"),
            SqlCompletion::function("STRING_TO_ARRAY()", "字符串转数组"),
            SqlCompletion::function("UNNEST()", "展开数组"),
            SqlCompletion::function("CARDINALITY()", "元素总数"),
            
            // 系统函数
            SqlCompletion::function("CURRENT_DATABASE()", "当前数据库"),
            SqlCompletion::function("CURRENT_SCHEMA()", "当前模式"),
            SqlCompletion::function("CURRENT_USER", "当前用户"),
            SqlCompletion::function("SESSION_USER", "会话用户"),
            SqlCompletion::function("USER", "用户"),
            SqlCompletion::function("VERSION()", "版本"),
            SqlCompletion::function("PG_TYPEOF()", "类型"),
            SqlCompletion::function("COALESCE()", "第一个非空"),
            SqlCompletion::function("NULLIF()", "相等返回空"),
            SqlCompletion::function("GREATEST()", "最大值"),
            SqlCompletion::function("LEAST()", "最小值"),
            SqlCompletion::function("GEN_RANDOM_UUID()", "生成 UUID"),
            SqlCompletion::function("MD5()", "MD5 哈希"),
            SqlCompletion::function("ENCODE()", "编码"),
            SqlCompletion::function("DECODE()", "解码"),
            SqlCompletion::function("PG_SLEEP()", "暂停"),
            SqlCompletion::function("PG_CANCEL_BACKEND()", "取消后端"),
            SqlCompletion::function("PG_TERMINATE_BACKEND()", "终止后端"),
        ]
    }
    
    fn data_types(&self) -> Vec<SqlCompletion> {
        vec![
            // 整数
            SqlCompletion::data_type("SMALLINT", "2 字节整数"),
            SqlCompletion::data_type("INT2", "2 字节整数"),
            SqlCompletion::data_type("INTEGER", "4 字节整数"),
            SqlCompletion::data_type("INT", "4 字节整数"),
            SqlCompletion::data_type("INT4", "4 字节整数"),
            SqlCompletion::data_type("BIGINT", "8 字节整数"),
            SqlCompletion::data_type("INT8", "8 字节整数"),
            SqlCompletion::data_type("SERIAL", "自增整数"),
            SqlCompletion::data_type("BIGSERIAL", "大自增整数"),
            SqlCompletion::data_type("SMALLSERIAL", "小自增整数"),
            
            // 浮点
            SqlCompletion::data_type("REAL", "单精度浮点"),
            SqlCompletion::data_type("FLOAT4", "单精度浮点"),
            SqlCompletion::data_type("DOUBLE PRECISION", "双精度浮点"),
            SqlCompletion::data_type("FLOAT8", "双精度浮点"),
            SqlCompletion::data_type("NUMERIC", "任意精度数"),
            SqlCompletion::data_type("DECIMAL", "任意精度数"),
            
            // 字符串
            SqlCompletion::data_type("CHAR", "定长字符串"),
            SqlCompletion::data_type("CHARACTER", "定长字符串"),
            SqlCompletion::data_type("VARCHAR", "变长字符串"),
            SqlCompletion::data_type("CHARACTER VARYING", "变长字符串"),
            SqlCompletion::data_type("TEXT", "文本"),
            
            // 二进制
            SqlCompletion::data_type("BYTEA", "二进制数据"),
            
            // 日期时间
            SqlCompletion::data_type("DATE", "日期"),
            SqlCompletion::data_type("TIME", "时间"),
            SqlCompletion::data_type("TIME WITH TIME ZONE", "带时区时间"),
            SqlCompletion::data_type("TIMETZ", "带时区时间"),
            SqlCompletion::data_type("TIMESTAMP", "时间戳"),
            SqlCompletion::data_type("TIMESTAMP WITH TIME ZONE", "带时区时间戳"),
            SqlCompletion::data_type("TIMESTAMPTZ", "带时区时间戳"),
            SqlCompletion::data_type("INTERVAL", "时间间隔"),
            
            // 布尔
            SqlCompletion::data_type("BOOLEAN", "布尔值"),
            SqlCompletion::data_type("BOOL", "布尔值"),
            
            // 几何
            SqlCompletion::data_type("POINT", "点"),
            SqlCompletion::data_type("LINE", "线"),
            SqlCompletion::data_type("LSEG", "线段"),
            SqlCompletion::data_type("BOX", "矩形"),
            SqlCompletion::data_type("PATH", "路径"),
            SqlCompletion::data_type("POLYGON", "多边形"),
            SqlCompletion::data_type("CIRCLE", "圆"),
            
            // 网络
            SqlCompletion::data_type("CIDR", "IPv4/IPv6 网络"),
            SqlCompletion::data_type("INET", "IPv4/IPv6 地址"),
            SqlCompletion::data_type("MACADDR", "MAC 地址"),
            SqlCompletion::data_type("MACADDR8", "MAC 地址 (8字节)"),
            
            // JSON
            SqlCompletion::data_type("JSON", "JSON"),
            SqlCompletion::data_type("JSONB", "二进制 JSON"),
            
            // 数组
            SqlCompletion::data_type("ARRAY", "数组"),
            
            // UUID
            SqlCompletion::data_type("UUID", "UUID"),
            
            // 其他
            SqlCompletion::data_type("XML", "XML"),
            SqlCompletion::data_type("MONEY", "货币"),
            SqlCompletion::data_type("BIT", "位串"),
            SqlCompletion::data_type("BIT VARYING", "变长位串"),
            SqlCompletion::data_type("VARBIT", "变长位串"),
            SqlCompletion::data_type("TSVECTOR", "文本搜索向量"),
            SqlCompletion::data_type("TSQUERY", "文本搜索查询"),
            SqlCompletion::data_type("HSTORE", "键值存储"),
        ]
    }
    
    fn operators(&self) -> Vec<SqlCompletion> {
        vec![
            SqlCompletion::keyword("=", "等于"),
            SqlCompletion::keyword("<>", "不等于"),
            SqlCompletion::keyword("!=", "不等于"),
            SqlCompletion::keyword(">", "大于"),
            SqlCompletion::keyword("<", "小于"),
            SqlCompletion::keyword(">=", "大于等于"),
            SqlCompletion::keyword("<=", "小于等于"),
            SqlCompletion::keyword("~", "正则匹配"),
            SqlCompletion::keyword("~*", "正则匹配（不区分大小写）"),
            SqlCompletion::keyword("!~", "正则不匹配"),
            SqlCompletion::keyword("!~*", "正则不匹配（不区分大小写）"),
            SqlCompletion::keyword("||", "连接"),
            SqlCompletion::keyword("->", "JSON 取值"),
            SqlCompletion::keyword("->>", "JSON 取文本"),
            SqlCompletion::keyword("#>", "JSON 路径取值"),
            SqlCompletion::keyword("#>>", "JSON 路径取文本"),
            SqlCompletion::keyword("@>", "包含"),
            SqlCompletion::keyword("<@", "被包含"),
            SqlCompletion::keyword("?", "JSON 键存在"),
            SqlCompletion::keyword("?|", "JSON 任一键存在"),
            SqlCompletion::keyword("?&", "JSON 所有键存在"),
            SqlCompletion::keyword("&&", "重叠"),
            SqlCompletion::keyword("@@", "全文搜索匹配"),
        ]
    }
    
    fn snippets(&self) -> Vec<SqlCompletion> {
        vec![
            SqlCompletion {
                text: "SELECT * FROM ".to_string(),
                description: "查询所有列".to_string(),
                kind: super::common::SqlCompletionKind::Snippet,
            },
            SqlCompletion {
                text: "SELECT COUNT(*) FROM ".to_string(),
                description: "统计行数".to_string(),
                kind: super::common::SqlCompletionKind::Snippet,
            },
            SqlCompletion {
                text: "INSERT INTO  () VALUES () RETURNING *".to_string(),
                description: "插入并返回".to_string(),
                kind: super::common::SqlCompletionKind::Snippet,
            },
            SqlCompletion {
                text: "UPDATE  SET  WHERE  RETURNING *".to_string(),
                description: "更新并返回".to_string(),
                kind: super::common::SqlCompletionKind::Snippet,
            },
            SqlCompletion {
                text: "DELETE FROM  WHERE  RETURNING *".to_string(),
                description: "删除并返回".to_string(),
                kind: super::common::SqlCompletionKind::Snippet,
            },
            SqlCompletion {
                text: "CREATE TABLE  (\n  id SERIAL PRIMARY KEY,\n  created_at TIMESTAMPTZ DEFAULT NOW(),\n  \n)".to_string(),
                description: "创建表模板".to_string(),
                kind: super::common::SqlCompletionKind::Snippet,
            },
            SqlCompletion {
                text: "WITH  AS (\n  \n)\nSELECT * FROM ".to_string(),
                description: "CTE 模板".to_string(),
                kind: super::common::SqlCompletionKind::Snippet,
            },
            SqlCompletion {
                text: "INSERT INTO  () VALUES ()\nON CONFLICT () DO UPDATE SET ".to_string(),
                description: "UPSERT 模板".to_string(),
                kind: super::common::SqlCompletionKind::Snippet,
            },
        ]
    }
}

