//! SQLite 语法定义

use super::common::{SqlCompletion, SqlSyntax};

/// SQLite 语法
pub struct SqliteSyntax;

impl SqlSyntax for SqliteSyntax {
    fn keywords(&self) -> Vec<SqlCompletion> {
        vec![
            // DML
            SqlCompletion::keyword("SELECT", "查询数据"),
            SqlCompletion::keyword("INSERT", "插入数据"),
            SqlCompletion::keyword("UPDATE", "更新数据"),
            SqlCompletion::keyword("DELETE", "删除数据"),
            SqlCompletion::keyword("REPLACE", "替换数据"),
            SqlCompletion::keyword("INSERT OR REPLACE", "插入或替换"),
            SqlCompletion::keyword("INSERT OR IGNORE", "插入或忽略"),
            SqlCompletion::keyword("INSERT OR ABORT", "插入或中止"),
            SqlCompletion::keyword("INSERT OR ROLLBACK", "插入或回滚"),
            SqlCompletion::keyword("INSERT OR FAIL", "插入或失败"),
            
            // 子句
            SqlCompletion::keyword("FROM", "数据来源"),
            SqlCompletion::keyword("WHERE", "条件过滤"),
            SqlCompletion::keyword("AND", "与条件"),
            SqlCompletion::keyword("OR", "或条件"),
            SqlCompletion::keyword("NOT", "非条件"),
            SqlCompletion::keyword("IN", "包含"),
            SqlCompletion::keyword("LIKE", "模糊匹配"),
            SqlCompletion::keyword("GLOB", "通配符匹配"),
            SqlCompletion::keyword("BETWEEN", "范围"),
            SqlCompletion::keyword("IS NULL", "空值判断"),
            SqlCompletion::keyword("IS NOT NULL", "非空判断"),
            SqlCompletion::keyword("EXISTS", "存在判断"),
            SqlCompletion::keyword("ORDER BY", "排序"),
            SqlCompletion::keyword("GROUP BY", "分组"),
            SqlCompletion::keyword("HAVING", "分组过滤"),
            SqlCompletion::keyword("LIMIT", "限制行数"),
            SqlCompletion::keyword("OFFSET", "偏移量"),
            SqlCompletion::keyword("DISTINCT", "去重"),
            SqlCompletion::keyword("AS", "别名"),
            SqlCompletion::keyword("ON", "连接条件"),
            SqlCompletion::keyword("USING", "使用列连接"),
            
            // JOIN
            SqlCompletion::keyword("JOIN", "连接表"),
            SqlCompletion::keyword("INNER JOIN", "内连接"),
            SqlCompletion::keyword("LEFT JOIN", "左连接"),
            SqlCompletion::keyword("LEFT OUTER JOIN", "左外连接"),
            SqlCompletion::keyword("CROSS JOIN", "交叉连接"),
            SqlCompletion::keyword("NATURAL JOIN", "自然连接"),
            SqlCompletion::keyword("NATURAL LEFT JOIN", "自然左连接"),
            
            // UNION
            SqlCompletion::keyword("UNION", "合并结果"),
            SqlCompletion::keyword("UNION ALL", "合并所有结果"),
            SqlCompletion::keyword("INTERSECT", "交集"),
            SqlCompletion::keyword("EXCEPT", "差集"),
            
            // CTE
            SqlCompletion::keyword("WITH", "公共表表达式"),
            SqlCompletion::keyword("WITH RECURSIVE", "递归CTE"),
            
            // DDL
            SqlCompletion::keyword("CREATE", "创建对象"),
            SqlCompletion::keyword("CREATE TABLE", "创建表"),
            SqlCompletion::keyword("CREATE TABLE IF NOT EXISTS", "创建表（如果不存在）"),
            SqlCompletion::keyword("CREATE TEMPORARY TABLE", "创建临时表"),
            SqlCompletion::keyword("CREATE TEMP TABLE", "创建临时表"),
            SqlCompletion::keyword("CREATE INDEX", "创建索引"),
            SqlCompletion::keyword("CREATE UNIQUE INDEX", "创建唯一索引"),
            SqlCompletion::keyword("CREATE VIEW", "创建视图"),
            SqlCompletion::keyword("CREATE TRIGGER", "创建触发器"),
            SqlCompletion::keyword("CREATE VIRTUAL TABLE", "创建虚拟表"),
            SqlCompletion::keyword("ALTER", "修改对象"),
            SqlCompletion::keyword("ALTER TABLE", "修改表"),
            SqlCompletion::keyword("DROP", "删除对象"),
            SqlCompletion::keyword("DROP TABLE", "删除表"),
            SqlCompletion::keyword("DROP TABLE IF EXISTS", "删除表（如果存在）"),
            SqlCompletion::keyword("DROP INDEX", "删除索引"),
            SqlCompletion::keyword("DROP VIEW", "删除视图"),
            SqlCompletion::keyword("DROP TRIGGER", "删除触发器"),
            
            // 表结构
            SqlCompletion::keyword("ADD", "添加列"),
            SqlCompletion::keyword("ADD COLUMN", "添加列"),
            SqlCompletion::keyword("RENAME TO", "重命名"),
            SqlCompletion::keyword("RENAME COLUMN", "重命名列"),
            SqlCompletion::keyword("DROP COLUMN", "删除列"),
            SqlCompletion::keyword("PRIMARY KEY", "主键"),
            SqlCompletion::keyword("FOREIGN KEY", "外键"),
            SqlCompletion::keyword("UNIQUE", "唯一约束"),
            SqlCompletion::keyword("CHECK", "检查约束"),
            SqlCompletion::keyword("CONSTRAINT", "约束"),
            SqlCompletion::keyword("DEFAULT", "默认值"),
            SqlCompletion::keyword("NOT NULL", "非空约束"),
            SqlCompletion::keyword("AUTOINCREMENT", "自增"),
            SqlCompletion::keyword("REFERENCES", "引用"),
            SqlCompletion::keyword("ON DELETE", "删除时"),
            SqlCompletion::keyword("ON UPDATE", "更新时"),
            SqlCompletion::keyword("CASCADE", "级联"),
            SqlCompletion::keyword("SET NULL", "置空"),
            SqlCompletion::keyword("SET DEFAULT", "设置默认"),
            SqlCompletion::keyword("RESTRICT", "限制"),
            SqlCompletion::keyword("NO ACTION", "无操作"),
            SqlCompletion::keyword("IF EXISTS", "如果存在"),
            SqlCompletion::keyword("IF NOT EXISTS", "如果不存在"),
            SqlCompletion::keyword("COLLATE", "排序规则"),
            SqlCompletion::keyword("COLLATE NOCASE", "不区分大小写"),
            SqlCompletion::keyword("COLLATE BINARY", "二进制比较"),
            SqlCompletion::keyword("COLLATE RTRIM", "去尾空格"),
            
            // TCL
            SqlCompletion::keyword("BEGIN", "开始事务"),
            SqlCompletion::keyword("BEGIN TRANSACTION", "开始事务"),
            SqlCompletion::keyword("BEGIN DEFERRED", "延迟事务"),
            SqlCompletion::keyword("BEGIN IMMEDIATE", "立即事务"),
            SqlCompletion::keyword("BEGIN EXCLUSIVE", "独占事务"),
            SqlCompletion::keyword("COMMIT", "提交事务"),
            SqlCompletion::keyword("END", "结束事务"),
            SqlCompletion::keyword("END TRANSACTION", "结束事务"),
            SqlCompletion::keyword("ROLLBACK", "回滚事务"),
            SqlCompletion::keyword("SAVEPOINT", "保存点"),
            SqlCompletion::keyword("RELEASE", "释放保存点"),
            SqlCompletion::keyword("RELEASE SAVEPOINT", "释放保存点"),
            SqlCompletion::keyword("ROLLBACK TO", "回滚到保存点"),
            
            // 其他
            SqlCompletion::keyword("EXPLAIN", "执行计划"),
            SqlCompletion::keyword("EXPLAIN QUERY PLAN", "查询计划"),
            SqlCompletion::keyword("ATTACH", "附加数据库"),
            SqlCompletion::keyword("ATTACH DATABASE", "附加数据库"),
            SqlCompletion::keyword("DETACH", "分离数据库"),
            SqlCompletion::keyword("DETACH DATABASE", "分离数据库"),
            SqlCompletion::keyword("VACUUM", "清理"),
            SqlCompletion::keyword("REINDEX", "重建索引"),
            SqlCompletion::keyword("ANALYZE", "分析统计"),
            SqlCompletion::keyword("PRAGMA", "配置"),
            SqlCompletion::keyword("INTO", "插入目标"),
            SqlCompletion::keyword("VALUES", "值列表"),
            SqlCompletion::keyword("CASE", "条件表达式"),
            SqlCompletion::keyword("WHEN", "当"),
            SqlCompletion::keyword("THEN", "则"),
            SqlCompletion::keyword("ELSE", "否则"),
            SqlCompletion::keyword("END", "结束"),
            SqlCompletion::keyword("COALESCE", "第一个非空"),
            SqlCompletion::keyword("NULLIF", "相等返回空"),
            SqlCompletion::keyword("IIF", "条件表达式"),
            SqlCompletion::keyword("ASC", "升序"),
            SqlCompletion::keyword("DESC", "降序"),
            SqlCompletion::keyword("NULLS FIRST", "空值在前"),
            SqlCompletion::keyword("NULLS LAST", "空值在后"),
            SqlCompletion::keyword("TRUE", "真"),
            SqlCompletion::keyword("FALSE", "假"),
            SqlCompletion::keyword("NULL", "空值"),
            
            // PRAGMA 常用选项
            SqlCompletion::keyword("PRAGMA table_info", "表结构"),
            SqlCompletion::keyword("PRAGMA table_list", "表列表"),
            SqlCompletion::keyword("PRAGMA database_list", "数据库列表"),
            SqlCompletion::keyword("PRAGMA index_list", "索引列表"),
            SqlCompletion::keyword("PRAGMA foreign_keys", "外键开关"),
            SqlCompletion::keyword("PRAGMA foreign_key_list", "外键列表"),
            SqlCompletion::keyword("PRAGMA journal_mode", "日志模式"),
            SqlCompletion::keyword("PRAGMA wal_checkpoint", "WAL 检查点"),
            SqlCompletion::keyword("PRAGMA synchronous", "同步模式"),
            SqlCompletion::keyword("PRAGMA cache_size", "缓存大小"),
            SqlCompletion::keyword("PRAGMA page_size", "页大小"),
            SqlCompletion::keyword("PRAGMA encoding", "编码"),
            SqlCompletion::keyword("PRAGMA user_version", "用户版本"),
            SqlCompletion::keyword("PRAGMA application_id", "应用 ID"),
            SqlCompletion::keyword("PRAGMA integrity_check", "完整性检查"),
            SqlCompletion::keyword("PRAGMA quick_check", "快速检查"),
            SqlCompletion::keyword("PRAGMA optimize", "优化"),
        ]
    }
    
    fn functions(&self) -> Vec<SqlCompletion> {
        vec![
            // 聚合函数
            SqlCompletion::function("COUNT()", "计数"),
            SqlCompletion::function("SUM()", "求和"),
            SqlCompletion::function("AVG()", "平均值"),
            SqlCompletion::function("MAX()", "最大值"),
            SqlCompletion::function("MIN()", "最小值"),
            SqlCompletion::function("TOTAL()", "总和（始终返回浮点）"),
            SqlCompletion::function("GROUP_CONCAT()", "分组连接"),
            
            // 窗口函数
            SqlCompletion::function("ROW_NUMBER()", "行号"),
            SqlCompletion::function("RANK()", "排名"),
            SqlCompletion::function("DENSE_RANK()", "密集排名"),
            SqlCompletion::function("PERCENT_RANK()", "百分比排名"),
            SqlCompletion::function("CUME_DIST()", "累积分布"),
            SqlCompletion::function("NTILE()", "分桶"),
            SqlCompletion::function("LAG()", "上一行"),
            SqlCompletion::function("LEAD()", "下一行"),
            SqlCompletion::function("FIRST_VALUE()", "第一个值"),
            SqlCompletion::function("LAST_VALUE()", "最后一个值"),
            SqlCompletion::function("NTH_VALUE()", "第 N 个值"),
            
            // 核心函数
            SqlCompletion::function("ABS()", "绝对值"),
            SqlCompletion::function("CHANGES()", "更改行数"),
            SqlCompletion::function("CHAR()", "ASCII 字符"),
            SqlCompletion::function("COALESCE()", "第一个非空"),
            SqlCompletion::function("GLOB()", "通配符匹配"),
            SqlCompletion::function("HEX()", "转十六进制"),
            SqlCompletion::function("IFNULL()", "空值替换"),
            SqlCompletion::function("IIF()", "条件表达式"),
            SqlCompletion::function("INSTR()", "查找位置"),
            SqlCompletion::function("LAST_INSERT_ROWID()", "最后插入行ID"),
            SqlCompletion::function("LENGTH()", "长度"),
            SqlCompletion::function("LIKE()", "模糊匹配"),
            SqlCompletion::function("LIKELIHOOD()", "概率提示"),
            SqlCompletion::function("LIKELY()", "可能为真"),
            SqlCompletion::function("LOAD_EXTENSION()", "加载扩展"),
            SqlCompletion::function("LOWER()", "转小写"),
            SqlCompletion::function("LTRIM()", "去左空格"),
            SqlCompletion::function("MAX()", "最大值"),
            SqlCompletion::function("MIN()", "最小值"),
            SqlCompletion::function("NULLIF()", "相等返回空"),
            SqlCompletion::function("PRINTF()", "格式化"),
            SqlCompletion::function("QUOTE()", "引用"),
            SqlCompletion::function("RANDOM()", "随机数"),
            SqlCompletion::function("RANDOMBLOB()", "随机二进制"),
            SqlCompletion::function("REPLACE()", "替换"),
            SqlCompletion::function("ROUND()", "四舍五入"),
            SqlCompletion::function("RTRIM()", "去右空格"),
            SqlCompletion::function("SIGN()", "符号"),
            SqlCompletion::function("SOUNDEX()", "发音编码"),
            SqlCompletion::function("SQLITE_COMPILEOPTION_GET()", "编译选项"),
            SqlCompletion::function("SQLITE_COMPILEOPTION_USED()", "是否使用编译选项"),
            SqlCompletion::function("SQLITE_OFFSET()", "偏移量"),
            SqlCompletion::function("SQLITE_SOURCE_ID()", "源 ID"),
            SqlCompletion::function("SQLITE_VERSION()", "版本"),
            SqlCompletion::function("SUBSTR()", "子字符串"),
            SqlCompletion::function("SUBSTRING()", "子字符串"),
            SqlCompletion::function("TOTAL_CHANGES()", "总更改数"),
            SqlCompletion::function("TRIM()", "去空格"),
            SqlCompletion::function("TYPEOF()", "类型"),
            SqlCompletion::function("UNICODE()", "Unicode 码"),
            SqlCompletion::function("UNLIKELY()", "可能为假"),
            SqlCompletion::function("UPPER()", "转大写"),
            SqlCompletion::function("ZEROBLOB()", "零二进制"),
            
            // 日期时间函数
            SqlCompletion::function("DATE()", "日期"),
            SqlCompletion::function("TIME()", "时间"),
            SqlCompletion::function("DATETIME()", "日期时间"),
            SqlCompletion::function("JULIANDAY()", "儒略日"),
            SqlCompletion::function("UNIXEPOCH()", "Unix 时间戳"),
            SqlCompletion::function("STRFTIME()", "格式化日期"),
            
            // 数学函数 (需要编译时启用)
            SqlCompletion::function("ACOS()", "反余弦"),
            SqlCompletion::function("ACOSH()", "反双曲余弦"),
            SqlCompletion::function("ASIN()", "反正弦"),
            SqlCompletion::function("ASINH()", "反双曲正弦"),
            SqlCompletion::function("ATAN()", "反正切"),
            SqlCompletion::function("ATAN2()", "二参数反正切"),
            SqlCompletion::function("ATANH()", "反双曲正切"),
            SqlCompletion::function("CEIL()", "向上取整"),
            SqlCompletion::function("CEILING()", "向上取整"),
            SqlCompletion::function("COS()", "余弦"),
            SqlCompletion::function("COSH()", "双曲余弦"),
            SqlCompletion::function("DEGREES()", "弧度转角度"),
            SqlCompletion::function("EXP()", "指数"),
            SqlCompletion::function("FLOOR()", "向下取整"),
            SqlCompletion::function("LN()", "自然对数"),
            SqlCompletion::function("LOG()", "自然对数"),
            SqlCompletion::function("LOG10()", "常用对数"),
            SqlCompletion::function("LOG2()", "二进制对数"),
            SqlCompletion::function("MOD()", "取模"),
            SqlCompletion::function("PI()", "圆周率"),
            SqlCompletion::function("POW()", "幂"),
            SqlCompletion::function("POWER()", "幂"),
            SqlCompletion::function("RADIANS()", "角度转弧度"),
            SqlCompletion::function("SIN()", "正弦"),
            SqlCompletion::function("SINH()", "双曲正弦"),
            SqlCompletion::function("SQRT()", "平方根"),
            SqlCompletion::function("TAN()", "正切"),
            SqlCompletion::function("TANH()", "双曲正切"),
            SqlCompletion::function("TRUNC()", "截断"),
            
            // JSON 函数
            SqlCompletion::function("JSON()", "验证 JSON"),
            SqlCompletion::function("JSON_ARRAY()", "创建数组"),
            SqlCompletion::function("JSON_ARRAY_LENGTH()", "数组长度"),
            SqlCompletion::function("JSON_EACH()", "遍历 JSON"),
            SqlCompletion::function("JSON_EXTRACT()", "提取值"),
            SqlCompletion::function("JSON_GROUP_ARRAY()", "聚合为数组"),
            SqlCompletion::function("JSON_GROUP_OBJECT()", "聚合为对象"),
            SqlCompletion::function("JSON_INSERT()", "插入值"),
            SqlCompletion::function("JSON_OBJECT()", "创建对象"),
            SqlCompletion::function("JSON_PATCH()", "合并 JSON"),
            SqlCompletion::function("JSON_QUOTE()", "引用"),
            SqlCompletion::function("JSON_REMOVE()", "删除值"),
            SqlCompletion::function("JSON_REPLACE()", "替换值"),
            SqlCompletion::function("JSON_SET()", "设置值"),
            SqlCompletion::function("JSON_TREE()", "JSON 树"),
            SqlCompletion::function("JSON_TYPE()", "值类型"),
            SqlCompletion::function("JSON_VALID()", "验证 JSON"),
        ]
    }
    
    fn data_types(&self) -> Vec<SqlCompletion> {
        vec![
            // SQLite 动态类型，但支持类型亲和性
            SqlCompletion::data_type("INTEGER", "整数"),
            SqlCompletion::data_type("INT", "整数"),
            SqlCompletion::data_type("TINYINT", "小整数"),
            SqlCompletion::data_type("SMALLINT", "小整数"),
            SqlCompletion::data_type("MEDIUMINT", "中整数"),
            SqlCompletion::data_type("BIGINT", "大整数"),
            SqlCompletion::data_type("UNSIGNED BIG INT", "无符号大整数"),
            SqlCompletion::data_type("INT2", "2字节整数"),
            SqlCompletion::data_type("INT8", "8字节整数"),
            
            SqlCompletion::data_type("REAL", "浮点数"),
            SqlCompletion::data_type("DOUBLE", "双精度"),
            SqlCompletion::data_type("DOUBLE PRECISION", "双精度"),
            SqlCompletion::data_type("FLOAT", "浮点数"),
            SqlCompletion::data_type("NUMERIC", "数值"),
            SqlCompletion::data_type("DECIMAL", "小数"),
            
            SqlCompletion::data_type("TEXT", "文本"),
            SqlCompletion::data_type("CHARACTER", "字符"),
            SqlCompletion::data_type("VARCHAR", "变长字符"),
            SqlCompletion::data_type("VARYING CHARACTER", "变长字符"),
            SqlCompletion::data_type("NCHAR", "国家字符"),
            SqlCompletion::data_type("NATIVE CHARACTER", "原生字符"),
            SqlCompletion::data_type("NVARCHAR", "国家变长字符"),
            SqlCompletion::data_type("CLOB", "字符大对象"),
            
            SqlCompletion::data_type("BLOB", "二进制大对象"),
            
            SqlCompletion::data_type("BOOLEAN", "布尔值"),
            
            SqlCompletion::data_type("DATE", "日期"),
            SqlCompletion::data_type("DATETIME", "日期时间"),
        ]
    }
    
    fn operators(&self) -> Vec<SqlCompletion> {
        vec![
            SqlCompletion::keyword("=", "等于"),
            SqlCompletion::keyword("==", "等于"),
            SqlCompletion::keyword("<>", "不等于"),
            SqlCompletion::keyword("!=", "不等于"),
            SqlCompletion::keyword(">", "大于"),
            SqlCompletion::keyword("<", "小于"),
            SqlCompletion::keyword(">=", "大于等于"),
            SqlCompletion::keyword("<=", "小于等于"),
            SqlCompletion::keyword("||", "连接字符串"),
            SqlCompletion::keyword("->", "JSON 提取"),
            SqlCompletion::keyword("->>", "JSON 提取文本"),
        ]
    }
    
    fn snippets(&self) -> Vec<SqlCompletion> {
        vec![
            SqlCompletion {
                text: "SELECT * FROM ".to_string(),
                description: "查询所有列".to_string(),
                kind: super::common::SqlCompletionKind::Snippet,
            },
            SqlCompletion {
                text: "SELECT COUNT(*) FROM ".to_string(),
                description: "统计行数".to_string(),
                kind: super::common::SqlCompletionKind::Snippet,
            },
            SqlCompletion {
                text: "INSERT INTO  () VALUES ()".to_string(),
                description: "插入数据".to_string(),
                kind: super::common::SqlCompletionKind::Snippet,
            },
            SqlCompletion {
                text: "INSERT OR REPLACE INTO  () VALUES ()".to_string(),
                description: "插入或替换".to_string(),
                kind: super::common::SqlCompletionKind::Snippet,
            },
            SqlCompletion {
                text: "UPDATE  SET  WHERE ".to_string(),
                description: "更新数据".to_string(),
                kind: super::common::SqlCompletionKind::Snippet,
            },
            SqlCompletion {
                text: "DELETE FROM  WHERE ".to_string(),
                description: "删除数据".to_string(),
                kind: super::common::SqlCompletionKind::Snippet,
            },
            SqlCompletion {
                text: "CREATE TABLE IF NOT EXISTS  (\n  id INTEGER PRIMARY KEY AUTOINCREMENT,\n  \n)".to_string(),
                description: "创建表模板".to_string(),
                kind: super::common::SqlCompletionKind::Snippet,
            },
            SqlCompletion {
                text: "CREATE INDEX IF NOT EXISTS  ON  ()".to_string(),
                description: "创建索引".to_string(),
                kind: super::common::SqlCompletionKind::Snippet,
            },
            SqlCompletion {
                text: "PRAGMA table_info()".to_string(),
                description: "查看表结构".to_string(),
                kind: super::common::SqlCompletionKind::Snippet,
            },
            SqlCompletion {
                text: ".tables".to_string(),
                description: "列出所有表".to_string(),
                kind: super::common::SqlCompletionKind::Snippet,
            },
            SqlCompletion {
                text: ".schema".to_string(),
                description: "查看表结构".to_string(),
                kind: super::common::SqlCompletionKind::Snippet,
            },
        ]
    }
}

